### ISSUE TITLE
Fallback element with `React.lazy`

### ISSUE THREAD

**Issue by Airkro** [liximomo/lazy-compile-webpack-plugin#4]
![image](https://user-images.githubusercontent.com/12206891/66793885-e0796980-ef31-11e9-95c4-460ba9c7431f.png)

**Comment by liximomo** [comment]
Can you provide an example repo?

**Comment by Airkro** [comment]
I’m tracking this issue when I’m not busy. I found that sometimes `() => import()` will return an empty object instead `Module{...}`.

**Comment by Airkro** [comment]
Now I use <https://webpack.js.org/configuration/experiments/#experimentslazycompilation> instead, close.
